# Generated by Django 6.1 on 2026-08-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
