# Generated by Django 6.1 on 2026-08-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotape',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
