# Generated by Django 6.1 on 2026-08-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_videotape_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotape',
            name='rating',
        ),
    ]
