# Generated by Django 6.1 on 2026-08-26 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_videotape_created_at_videotape_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='videotape',
            name='rental_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_tapes', to='app.rentalstore'),
        ),
    ]
