# Generated by Django 6.1 on 2026-08-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_school_teacher_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(max_length=300),
        ),
    ]
