# Generated by Django 6.1 on 2026-09-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GamingPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.CharField(max_length=200)),
                ('cpu', models.CharField(max_length=200)),
                ('gpu', models.CharField(max_length=200)),
            ],
        ),
    ]
