# Generated by Django 6.1 on 2026-09-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('horsepower', models.IntegerField()),
                ('apple_car_play', models.BooleanField(default=False)),
                ('google_play', models.BooleanField(default=False)),
                ('base_price', models.IntegerField()),
            ],
        ),
    ]
